name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # Exécute chaque jour à minuit
  workflow_dispatch:  # Permet de lancer manuellement

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: Ahm778
          outputs: dist/snake.svg

      - uses: actions/upload-artifact@v3
        with:
          name: snake-animation
          path: dist/snake.svg
